config/routes.rb
Rails.application.routes.draw do
    
  devise_for :users, controllers: {sessions: "sessions", users: "users"}

  concern :the_role, TheRole::AdminRoutes.new

  namespace :admin do
    concerns :the_role
  end

# :controllers => { :sessions => 'users/sessions' }
  
  resources :orders do
    collection do
      get 'wnioski'
    end
    member do
      patch 'zatwierdz'
      patch 'potwierdz'
    end
  resource :decisions
  end

  resources :order_items, only: [:show, :create, :edit, :update, :destroy] do
    resources :areas
  end

  resources :products
  resources :workers
  resources :branches


  get '/pomoc', to: 'static_pages#pomoc'
  get 'static_pages/pomoc'

  root 'products#index'
end

app/models/decision.rb
class Decision < ActiveRecord::Base
	belongs_to :order
	
end

app/controllers/decisions_controller.rb
class DecisionsController < ApplicationController
  before_action :set_decision, only: [:show, :edit, :update, :destroy]

  # GET /decisions
  # GET /decisions.json
  def index
    @decisions = Decision.all
  end

  # GET /decisions/1
  # GET /decisions/1.json
  def show
  end

  # GET /decisions/new
  def new
    @decision = Decision.new
  end

  # GET /decisions/1/edit
  def edit
  end

  # POST /decisions
  # POST /decisions.json
  def create

    @order = Order.find(params[:order_id])
    if @order.decision.nil? && ( @order.potwierdzony? || @order.abipotwierdzam? || @order.goupotwierdzam? )
      @decision = @order.build_decision(decision_params)
        if @decision.save
          if @decision.opinia == false
            @order.brak_zgody
            flash[:error] = "Wniosek został odrzucony"
          else @decision.opinia == true
            @order.gau_potwierdzam
            flash[:success] = "Wniosek został zaakceptowany"
          end 
          redirect_to @order
        else
          redirect_to @order
        end
    elsif !@order.decision.nil?
     flash[:error] = "Wniosek posiada już decyzję"
     redirect_to @order 
    else
     flash[:error] = "Wniosek jest w obiegu"
     redirect_to @order 
    end
  end

  # PATCH/PUT /decisions/1
  # PATCH/PUT /decisions/1.json
  def update
    respond_to do |format|
      if @decision.update(decision_params)
        format.html { redirect_to @decision, notice: 'Decision was successfully updated.' }
        format.json { render :show, status: :ok, location: @decision }
      else
        format.html { render :edit }
        format.json { render json: @decision.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /decisions/1
  # DELETE /decisions/1.json
  def destroy
    @decision.destroy
    respond_to do |format|
      format.html { redirect_to decisions_url, notice: 'Decision was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_decision
      @decision = Decision.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def decision_params
      params.require(:decision).permit(:order_id, :opinia)
    end
end

app/helpers/decisions_helper.rb
module DecisionsHelper
end

app/views/decisions/_form.html.erb
<%= simple_form_for(@decision) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :opinia %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/decisions/edit.html.erb
<h1>Editing decision</h1>

<%= render 'form' %>

<%= link_to 'Show', @decision %> |
<%= link_to 'Back', decisions_path %>

app/views/decisions/index.html.erb
<h1>Listing decisions</h1>

<table>
  <thead>
    <tr>
      <th>Opinia</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @decisions.each do |decision| %>
      <tr>
        <td><%= decision.opinia %></td>
        <td><%= link_to 'Show', decision %></td>
        <td><%= link_to 'Edit', edit_decision_path(decision) %></td>
        <td><%= link_to 'Destroy', decision, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Decision', new_decision_path %>

app/views/decisions/new.html.erb
<h1>New decision</h1>

<%= render 'form' %>

<%= link_to 'Back', decisions_path %>

app/views/decisions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Opinia:</strong>
  <%= @decision.opinia %>
</p>

<%= link_to 'Edit', edit_decision_path(@decision) %> |
<%= link_to 'Back', decisions_path %>