config/routes.rb
Rails.application.routes.draw do
    
  devise_for :users, controllers: {sessions: "sessions", users: "users"}

  concern :the_role, TheRole::AdminRoutes.new

  namespace :admin do
    concerns :the_role
  end

# :controllers => { :sessions => 'users/sessions' }
  
  resources :orders do
    collection do
      get 'wnioski'
    end
    member do
      patch 'zatwierdz'
      patch 'potwierdz'
    end
  resource :decisions
  end

  resources :order_items, only: [:show, :create, :edit, :update, :destroy] do
    resources :areas
  end

  resources :products
  resources :workers
  resources :branches


  get '/pomoc', to: 'static_pages#pomoc'
  get 'static_pages/pomoc'

  root 'products#index'
end

app/models/order.rb
class Order < ActiveRecord::Base
	default_scope { order('created_at DESC') }
	scope :nowe, -> { where(status: 1)} #Zaakceptepowane przez wnioskującego
	scope :potw, -> { where(status: 2)} #Zaakceptowane przez Koordynator
	scope :abii, -> { where(status: 4)} #Zaakceptowane przez ABI
	scope :gou, -> { where(status: 8)}	#Zaakceptowane przez GOU
	scope :dane_osob, -> { where(status: 2, dane_osobowe: true)}
	scope :upr_lok, -> { where(uprlok: true) }
	scope :upr_glowne, -> { where(uprlok: false) }

	has_one :decision
	
	has_many :order_items, dependent: :destroy
	has_many :products, through: :order_items
	has_many :branches, through: :users

	has_and_belongs_to_many :users
	has_and_belongs_to_many :contributors, class_name: 'User'


	enum status: [
								:niezatwierdzony, #Status wniosku zainicjowanego
					 			:wobiegu, 				#Status wniosku wysłanego do akceptacji
					 			:potwierdzony, 		#Status wniosku potwierdzonego przez Koordynatora
					 			:kordpopr, 				#Status wniosku wystawionego do poprawy przez Koordynatora
					 			:abipotwierdzam,	#Status wniosku potwierdzonego przez ABI
					 			:odrzucony,				#Status wniosku odrzuconego
					 			:lokpotwierdzam,	#Status wniosku potwierdzonego przez Lokalnego Właściciela Danych
					 			:dyrpotwierdzam,		#Status wniosku potwierdzonego przez Dyrektora
					 			:goupotwierdzam,		#Status wniosku potwierdzonego przez GOU
					 			:gaupotwierdzam
					 											]


	def akcept
		self.wobiegu! if status == "niezatwierdzony" 
	end

	def potwierdzam
		self.potwierdzony! if status == "wobiegu"
	end

	def abi_potwierdzam
		self.abipotwierdzam! if status == "potwierdzony"
	end

	def lok_potwierdzam
		self.lokpotwierdzam! if status == "abipotwierdzam" || status == "potwierdzony"
	end

	def self.lokpotwierdzam?
		status == "lokpotwierdzam"
	end

	def dyr_potwierdzam
		self.dyrpotwierdzam! if status == "abipotwierdzam" || status == "potwierdzony"
	end

	def gou_potwierdzam
		self.goupotwierdzam! if status == "dyrpotwierdzam"
	end

	def gau_potwierdzam
		self.gaupotwierdzam! if status == "goupotwierdzam"
	end

	def brak_zgody
		self.odrzucony!
	end

	def sprawdz_status
		if status == "niezatwierdzony"
			return "Niezatwierdzony"
		elsif status == "wobiegu"
			return "W obiegu"
		elsif status == "potwierdzony"
			return "Potwierdzony przez Koordynatora"
		elsif status == "kordpopr"
			return "Do poprawy"
		elsif status == "abipotwierdzam"
			return "Potwierdzony przez ABI"
		elsif status == "odrzucony"
			return "Wniosek odrzucony"
		elsif status == "lokpotwierdzam"
			return "Potwierdzony przez LOK ADM"
		elsif status == "dyrpotwierdzam"
			return "Potwierdzony przez Dyrektora"
		elsif status == "goupotwierdzam"
			return "Potwierdzony przez GOU"
		elsif status == "gaupotwierdzam"
			return "Wniosek zrealizowany"
		end
	end

	def oddzial_wnioskujacego
		unless users.blank?
			users.first.branch.nazwa
		end
	end

	def upr_lok?
		self.uprlok == true
	end

	def dane_osobowe?
		self.dane_osobowe == true
	end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :role_required
  before_action :find_ord, only: [:index]
  before_action :set_order, only: [:show, :edit, :update, :destroy, :zatwierdz, :potwierdz]
  #before_action :owner_required, only: [:update, :destroy]
  # GET /orders
  # GET /orders.json
  def index
    # => Admin
    if current_user.admin?
      @ord = Order.all.paginate(:page => params[:page], :per_page => 10).uniq
    # => Koordynator
    elsif current_user.kord?
      branch = current_user.branch
      @ord = branch.orders.paginate(:page => params[:page], :per_page => 10).uniq
    # => Kierownik działu
    elsif current_user.kier? 
      branch = current_user.branch
      @ord = branch.orders.paginate(:page => params[:page], :per_page => 10).uniq
    elsif current_user.abi?
    # => ABI
      branch = current_user.branch
      @ord = branch.orders.dane_osob.paginate(:page => params[:page], :per_page => 10).uniq 
    elsif current_user.lokwl?
    # => Lokalny Właściciel Danych
      branch = current_user.branch
      #@ord = branch.orders.upr_lok.joins(:products, :users).where(users: { id: current_user.id}).uniq,
      @ord = branch.orders.upr_lok.select{ |x| x.products.select{|z| z.users.include?(current_user)}}.uniq
    elsif current_user.dyrektor?
    # => Dyrektor Oddziału
      branch = current_user.branch
      @ord = branch.orders.upr_glowne.paginate(:page => params[:page], :per_page => 10).uniq
    elsif current_user.gou?
    # => Główny Odbiorca Usług
      @ord = Order.all.upr_glowne.select{ |x| x.products.select{|z| z.assistants.include?(current_user)}}.uniq
    elsif current_user.gau?
    # => Główny Administrator Uprawnień
      @ord = Order.all
    end
    # => Wnioski uzytkownika
    @orders = current_user.orders
  end
  #Order.all.select{ |x| x.products.select{|z| z.users.include?(u)}}

  # GET /orders/1
  # GET /orders/1.json
  def show
    @user = current_user
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
    @prac = User.select{|x| x.branch == current_user.branch }
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = current_user.orders.create(order_params)
     respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    if @order.niezatwierdzony? && params[:order][:kordkom].nil? && @order.update_attributes(order_params)
      redirect_to @order, notice: "Pracownicy zostali dodani do wniosku"
    elsif !params[:order][:kordkom].nil?
      @order.kordpopr!
      @order.kordkom = params[:order][:kordkom]
      flash[:success] = 'Wniosek został przesłany do poprawy'
      redirect_to @order
    else
      redirect_to @order
      flash[:error] = "Na tym etapie nie możesz edytować wniosku"
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy

    if @order.niezatwierdzony? || @order.kordkom?
      @order.destroy
      respond_to do |format|
        format.html { redirect_to root_url }
        flash[:success] = "Wniosek został usunięty"
        format.json { head :no_content }
      end
    else
      redirect_to @order
      flash[:error] = "Na tym etapie nie możesz usunąć wniosku"
    end
  end

  def zatwierdz
    if @order.order_items.empty? || @order.contributors.count == 0
      redirect_to @order
      flash[:error] = "Wniosek nie posiada ról lub nie zostali przypisani pracownicy"
    elsif @order.niezatwierdzony?
      @order.akcept
      session[:order_id] = nil
      redirect_to @order
      flash[:success] = "Twój wniosek został przesłany do realizacji"
    elsif @order.potwierdzony? && current_user.abi?
      @order.abi_potwierdzam
      flash[:success] = "Wniosek został potwierdzony przez ABI"
      redirect_to @order
    elsif current_user.lokwl? && ( @order.potwierdzony? || @order.abipotwierdzam? )
      @order.lok_potwierdzam
      flash[:success] = "Wniosek został potwierdzony przez Lokalnego Właściciela Danych"
      redirect_to @order
    elsif current_user.dyrektor? && ( @order.potwierdzony? || @order.abipotwierdzam? )
      @order.dyr_potwierdzam
      flash[:success] = "Wniosek został potwierdzony przez dyrektora"
      redirect_to @order
    elsif current_user.gou? && @order.dyrpotwierdzam?
      @order.gou_potwierdzam
      flash[:success] = "Wniosek został potwierdzony przez GOU"
      redirect_to @order
    else
      flash[:error] = "Wniosek jest w trakcie realizacji"
      redirect_to :back
    end
  end

  def potwierdz
     #current_user.kier? && @order.wobiegu?
    if @order.potwierdzam
      redirect_to @order
      flash[:success] = "Wniosek został potwierdzony"
    else
      redirect_to @order
      flash[:error] = "Wniosek został już potwierdzony"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
      @owner_check_object = @order
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:status, :kordkom, :user_ids => [], :contributor_ids => [])
    end


end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
 

  <div class="form-inputs">
  	<%#= hidden_field_tag "order[contributor_ids][]", nil %>
    

    <%# @prac.each do |contributor| %>


      <%#= check_box_tag "order[contributor_ids][]", contributor.id, @order.contributor_ids.include?(contributor.id), id: dom_id(contributor) %>

      
      <%#= label_tag dom_id(contributor), contributor %>

    <%# end %>
      <%= collection_check_boxes(:order, :contributor_ids, @prac, :id, :to_s) %> 
  </div>

  <div class="form-actions">
    <%= f.button "Dodaj pracownika", class: 'btn btn-success', data: { disable_with: "<i class='fa fa-spinner fa-spin'></i> Dodawanie pracownika..."} %>
  </div>
<% end %>

app/views/orders/_popraw.haml
#komentarz
  .row
    .span8
      %h6 Wniosek nieprawidłowo wypełniony?

      = simple_form_for(@order) do |f|
        = f.error_notification
        .form-inputs
          = f.input :kordkom, placeholder: 'Dodaj komentarz', :label => false, :input_html => { :rows => 6, :style => "width: 100%;" }
        .form-actions
          = f.button :submit, "Prześlij", class: 'btn btn-primary'

app/views/orders/_sub.html.erb


  <div class="form-inputs">
    <%= object.input :email, required: true, autofocus: true %>
    <%= object.input :password, required: true %>
    <%= object.input :password_confirmation, required: true %>
  </div>

  <div class="form-actions">
    <%= object.button :submit %>
  </div>

app/views/orders/_wnioski.haml
%table.table
  %thead
    %tr
      %th ID
      %th Wnioskujący
      %th Status
      %th Utworzony
      %th Modyfikacja

  %tbody
    - @ord.each do |o|
      - if o.gaupotwierdzam?
        %tr.statusik
          %td= link_to o.id, o
          %td= o.wnioskujacy
          %td= o.sprawdz_status
          %td= o.created_at.strftime('%Y:%m:%d')
          %td= o.updated_at.strftime('%Y:%m:%d')
      - else
        %tr
          %td= link_to o.id, o
          %td= o.wnioskujacy
          %td= o.sprawdz_status
          %td= o.created_at.strftime('%Y:%m:%d')
          %td= o.updated_at.strftime('%Y:%m:%d')

app/views/orders/edit.html.erb
<h1>Aktualizacja wniosku</h1>

<%= render 'form' %>

<%= link_to 'Przejdz do wniosku', @order %> |
<%= link_to 'Wszystkie wnioski', orders_path %>

app/views/orders/index.haml
- if current_user.admin?
	.page-header
		%h2 Wnioski pracowników
	.row
		.span8
			%table.table
				%tbody
					- @ord.each do |ord|
						%tr
							%td= link_to ord.id, ord
							%td= ord.wnioskujacy
							%td= ord.sprawdz_status
							%td= ord.updated_at
							%td= ord.created_at
	
	= will_paginate @ord

	.row
		.span8
			= @ord.nowe.count 
			wniosków oczekujących na akceptacje koordynatora

		.span8
			= @ord.potw.count 
			wniosków zaakceptowanych przez koordynatora

		.span8
			= @ord.abii.count 
			wniosków zaakceptowanych przez ABI
			
		.span8
			= @ord.dane_osob.count 
			wniosków przetwarzających dane osobowe

- elsif current_user.kier?
	.page-header
		%h2 Wnioski pracowników Oddziału 
		#{current_user.branch}
	%table.table
		%thead
			%tr
				%th ID
				%th Wnioskujący
				%th Status
				%th Utworzony
				%th Modyfikacja
		%tbody
			- @ord.each do |o|
				%tr
					%td= link_to o.id, o
					%td= o.wnioskujacy
					%td= o.sprawdz_status
					%td= o.created_at
					%td= o.updated_at
	
	= will_paginate @ord

	.row
		.span8
			= @ord.nowe.count 
			wniosków oczekujących na akceptacje koordynatora

		.span8
			= @ord.potw.count 
			wniosków zaakceptowanych przez koordynatora

		.span8
			= @ord.abii.count 
			wniosków zaakceptowanych przez ABI
			
		.span8
			= @ord.dane_osob.count 
			wniosków przetwarzających dane osobowe

- elsif current_user.kord?
	.page-header
		%h2 
			Wnioski pracowników Oddziału 
			#{current_user.branch}
	%table.table
		%thead
			%tr
				%th ID
				%th Wnioskujący
				%th Status
				%th Utworzony
				%th Modyfikacja

		%tbody
			- @ord.each do |o|
				%tr
					%td= link_to o.id, o
					%td= o.wnioskujacy
					%td= o.sprawdz_status
					%td= o.created_at
					%td= o.updated_at

	= will_paginate @ord

	.row
		.span8
			= @ord.nowe.count 
			wniosków oczekujących na akceptacje koordynatora

		.span8
			= @ord.potw.count 
			wniosków zaakceptowanych przez koordynatora

		.span8
			= @ord.abii.count 
			wniosków zaakceptowanych przez ABI
			
		.span8
			= @ord.dane_osob.count 
			wniosków przetwarzających dane osobowe

- elsif current_user.abi?
	.page-header
		%h2 Wnioski pracowników Oddziału #{current_user.branch}

	%table.table
		%thead
			%tr
				%th ID
				%th Wnioskujący
				%th Status
				%th Utworzony
				%th Modyfikacja


		%tbody
			- @ord.each do |o|
				%tr
					%td= link_to o.id, o
					%td= o.wnioskujacy
					%td= o.sprawdz_status
					%td= o.created_at
					%td= o.updated_at

	= will_paginate @ord

	.row
		.span8
			= @ord.nowe.count 
			wniosków oczekujących na akceptacje koordynatora

		.span8
			= @ord.potw.count 
			wniosków zaakceptowanych przez koordynatora

		.span8
			= @ord.abii.count 
			wniosków zaakceptowanych przez ABI
			
		.span8
			= @ord.dane_osob.count 
			wniosków przetwarzających dane osobowe

- elsif current_user.lokwl?
	.page-header
		%h2 
			Witaj Lokalny Właścicielu Danych - Wnioski pracowników Oddziału 
			#{current_user.branch}
	%table.table
		%thead
			%tr
				%th ID
				%th Wnioskujący
				%th Status
				%th Utworzony
				%th Modyfikacja

		%tbody
			- @ord.each do |o|
				%tr
					%td= link_to o.id, o
					%td= o.wnioskujacy
					%td= o.sprawdz_status
					%td= o.created_at
					%td= o.updated_at

- elsif current_user.dyrektor?
	.page-header
		%h2 
			Witaj Dyrektorze - Wnioski pracowników Oddziału 
			#{current_user.branch}
	%table.table
		%thead
			%tr
				%th ID
				%th Wnioskujący
				%th Status
				%th Utworzony
				%th Modyfikacja

		%tbody
			- @ord.each do |o|
				%tr
					%td= link_to o.id, o
					%td= o.wnioskujacy
					%td= o.sprawdz_status
					%td= o.created_at
					%td= o.updated_at	

- elsif current_user.gou?
	.page-header
		%h2 
			Witaj GOU - Wnioski pracowników KW SA
	%table.table
		%thead
			%tr
				%th ID
				%th Wnioskujący
				%th Status
				%th Utworzony
				%th Modyfikacja

		%tbody
			- @ord.each do |o|
				%tr
					%td= link_to o.id, o
					%td= o.wnioskujacy
					%td= o.sprawdz_status
					%td= o.created_at
					%td= o.updated_at			

- elsif current_user.gau?
	.page-header
		%h2 
			Witaj Główny Administratorze Uprawnień
	
	= render 'wnioski'			

app/views/orders/kopiashow.html.erb
<div class="row well wniosek">
		<div class="span8 page-header">
			<h3>KW S.A. Oddział <%= @order.oddzial_wnioskujacego %></h3>
			Wniosek o nadanie, modyfikację lub usunięcie uprawnień do systemów informatycznych.
		</div>

		<div class="order-body span8">
			<div class="row">
				<h4>Dane użytkownika:</h4>
				
				<div class="span4">
					<strong>Wnioskujący:</strong>
				</div>
				<div class="span4">
					<%= @order.wnioskujacy %>		
				</div>
				
				<div class="span4">
					<strong>Email:</strong>
				</div>
				
				<div class="span4">
					test1@test.com<%#= @order.wnioskujacy %>		
				</div>
				
				<div class="span4">
					<strong>Oddział</strong>
				</div>
				<div class="span4">
					<%= @order.oddzial_wnioskujacego %>		
				</div>
				
				<div class="span4">
					<strong>Biuro</strong>
				</div>
				<div class="span4">
					<%= @order.wnioskujacy %>		
				</div>				
				
				<div class="span4">
					<strong>Nr telefonu</strong>
				</div>
				<div class="span4">
					32 716 66 26
				</div>				
				
				
				<div class="span4">
					<strong>Nowy pracownik?:</strong>
				</div>
				<div class="span4">
					<%= link_to "Dodaj pracownika", '#' %>
				</div>
				<div class="span4">
					<strong>Status:</strong>
				</div>
				<div class="span4">
					<%= @order.sprawdz_status %>
				</div>				
			<% unless @order.kordkom.nil? %>
				<div class="span4">
					<strong>Komentarz:</strong>
				</div>
				<div class="span4">
					%= @order.kordkom %>
				</div>	
			<% end %>
			</div>

			<p>
				<strong>Ilość ról:</strong>
				<%= @order.order_items.count %>
			</p>
			<p>
				<p>
					<%= render @order.order_items %>
				</p>
			</p>
		
		
	<% unless @order.contributors.blank? %>

		<table class="table">
		  <thead>
		    <tr>
		      <th>Uprawnienia dla:</th>
		      <th>Oddział</th>
		    </tr>
		  </thead>
		  

		  <tbody>
		    <% @order.contributors.each do |cont| %>
		      <tr>
		        <td><%= cont %></td>
		        <td><%= cont.branch unless cont.branch.blank? %></td>
		      </tr>
		    <% end %>
		  </tbody>
		</table>

	<% end %>

	<% @branche = current_user.branch %>
	<% @users = @branche.users %>

		<table class="table">
		  <thead>
		    <tr>
		      <th>Uprawnienia dla:</th>
		      <th>Ilość wniosków</th>
		    </tr>
		  </thead>

		  <tbody>
		    <% @users.each do |worker| %>
		      <tr>
		        <td><%= worker %></td>
		        <td><%= worker.orders.count %></td>
		      </tr>
		    <% end %>
		  </tbody>
		</table>

	<% if @order.decision && @order.decision.opinia %>
		<div class="row decyzja">			
			<div class="span9">
				<b><p>Wniosek ZAAKCEPTOWANY</p></b>
			</div>
		</div>
	<% elsif @order.decision.present? && @order.decision.opinia == false %>
		<div class="row decyzja-od">			
			<div class="span9">
				<b><p>Wniosek ODRZUCONY</p></b>
			</div>
		</div>
	<% end %>


	<%= link_to "Usuń wniosek", @order, data: { confirm: 'Usunąć wniosek?' }, method: :delete %>

	<% if current_user.kier? %>
		<%= link_to 'Dodaj pracownika do wniosku', edit_order_path(@order) %>
		<%= link_to 'Zatwierdz do realizacji', zatwierdz_order_path, method: :patch %>
	<% elsif current_user.kord? %>
	 	<%= link_to 'Potwierdz', potwierdz_order_path, method: :patch %>

	 	<%= render partial: "popraw" %>

	<% elsif current_user.abi? %>
		<%= link_to 'Akceptuje', zatwierdz_order_path, method: :patch %>
		<%= link_to "Brak zgody", order_decisions_path(@order, :decision => {:opinia => false}), :method => :post %>
	<% end %>

	<%= link_to 'Back', orders_path %>
	
	</div>
</div>


app/views/orders/show.haml
.row.well.wniosek
	.span8.page-header
		%h3 
			KW S.A. #{@order.oddzial_wnioskujacego}
		Wniosek id: <strong> #{@order.id} </strong> o nadanie, modyfikację lub usunięcie uprawnień do systemów informatycznych.

	.order-body.span8
		.row
			%h4 Dane użytkownika:
			
			.span4
				%strong Wnioskujący:
			.span4
				= @order.wnioskujacy
			
			.span4
				%strong Email:
			.span4
				test1@test.com		
			
			.span4
				%strong Oddział
			.span4
				= @order.oddzial_wnioskujacego
						
			.span4
				%strong Biuro
			.span4
				= @order.wnioskujacy
			
			.span4
				%strong Nr telefonu
			.span4
				32 716 66 26				
			
			.span4
				%strong Nowy pracownik?
			.span4
				= link_to "Dodaj pracownika", '#'

			.span4
				%strong Status:
			.span4
				= @order.sprawdz_status

			- if @order.lokpotwierdzam?
				.span4
					%strong Wniosek do nadania
			
			- unless @order.kordkom.nil?
				.span4
					%strong Komentarz:
				.span4
					= @order.kordkom

			&nbsp;
			.span8.roleklas
				%h4 Uprawnienia do systemów:
				= render @order.order_items
		
			- unless @order.contributors.blank?

				%table.table.uprawnieni
					%thead
						%tr
							%th 
								%h4 Uprawnienia dla:
							%th Oddział

					%tbody
						- @order.contributors.each do |cont|
							%tr
								%td= cont
								%td= cont.branch unless cont.branch.blank?
					 
			- if @order.decision && @order.decision.opinia
				.row#decyzja			
					.span8
						.well
							%h6.pager
								Wniosek ZAAKCEPTOWANY
			- elsif @order.decision.present? && @order.decision.opinia == false
				.row.decyzja-od			
					.span8
						%b
							%p Wniosek ODRZUCONY

			- if current_user.kier? && @order.niezatwierdzony?
				.well
					= link_to 'Dodaj pracownika do wniosku', edit_order_path(@order), class: 'btn btn-warning btn-block'
					= link_to 'Zatwierdz do realizacji', zatwierdz_order_path, method: :patch, class: 'btn btn-success btn-block'
					= link_to "Usuń wniosek", @order, data: { confirm: 'Usunąć wniosek?' }, method: :delete, class: 'btn btn-danger btn-block'

			- elsif current_user.kord?
				.well
					= link_to 'Potwierdz', potwierdz_order_path, method: :patch, class: 'btn btn-success btn-block'

				= render partial: "popraw"

			- elsif ( current_user.abi? && @order.decision.nil? ) || current_user.lokwl? || current_user.dyrektor? || current_user.gou? 
				.well
					= link_to 'Akceptuje', zatwierdz_order_path, method: :patch, class: 'btn btn-success btn-block'
					= link_to "Brak zgody", order_decisions_path(@order, :decision => {:opinia => false}), :method => :post, class: 'btn btn-warning btn-block'
			- elsif current_user.gau?
				- if @order.decision.nil?
					.well
						= link_to "Uprawnienia nadane", order_decisions_path(@order, :decision => { :opinia => true }), :method => :post, class: 'btn btn-success btn-block'
						= link_to "Brak zgody", order_decisions_path(@order, :decision => {:opinia => false}), :method => :post, class: 'btn btn-warning btn-block'

= link_to 'Wszystkie wnioski', orders_path

