config/routes.rb
Rails.application.routes.draw do
    
  devise_for :users, controllers: {sessions: "sessions", users: "users"}

  concern :the_role, TheRole::AdminRoutes.new

  namespace :admin do
    concerns :the_role
  end

# :controllers => { :sessions => 'users/sessions' }
  
  resources :orders do
    collection do
      get 'wnioski'
    end
    member do
      patch 'zatwierdz'
      patch 'potwierdz'
    end
  resource :decisions
  end

  resources :order_items, only: [:show, :create, :edit, :update, :destroy] do
    resources :areas
  end

  resources :products
  resources :workers
  resources :branches


  get '/pomoc', to: 'static_pages#pomoc'
  get 'static_pages/pomoc'

  root 'products#index'
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
	belongs_to :order
	belongs_to :product
  has_and_belongs_to_many :branches
  
	validates :product_id, :uniqueness => { :scope => :order_id, :message => "Wnioskujesz już o tą role" }
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_order_item, only: [:show, :edit, :update, :destroy]
  before_action :role_required
  before_action :find_ord, only: [:create, :update, :destroy]
  after_action  :check_dane_osobowe, only: [:create]
  after_action  :check_uprawnienia_lokalne, only: [:update]
  # GET /order_items/1/edit
  def index
    @order_items = OrderItem.all
  end

  def show
  end

  def edit
    unless @order_item.order.niezatwierdzony?
      redirect_to @order_item.order
      flash[:error] = "Na tym etapie nie ma możliwości edytowania wniosku"
    end
  end


  # POST /order_items
  # POST /order_items.json
  def create
    order_item = @order.order_items.create(product_id: params[:product_id] )

    respond_to do |format|
      if order_item.save
        format.html { redirect_to root_url }
        flash[:success] = "Rola została dodana do wniosku"
        format.json { render :show, status: :created, location: order_item }
      else
        format.html { redirect_to root_url }
        flash[:error] = "Wnioskujesz już o tą rolę"
        format.json { render json: order_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /order_items/1
  # PATCH/PUT /order_items/1.json
  def update
    if @order_item.order.niezatwierdzony? && @order_item.update_attributes(order_item_params)
      redirect_to @order_item.order 
      flash[:success] = 'Order item was successfully updated.' 
    else
      format.html { render :edit }
    end
  end

  # DELETE /order_items/1
  # DELETE /order_items/1.json
  def destroy
    order = @order_item.order
    if order.niezatwierdzony?
      @order_item.destroy
      respond_to do |format|
        format.html { redirect_to @order }
        flash[:success] = "Rola została usunięta z wniosku"
        format.json { head :no_content }
      end
    else
      flash[:error] = "Wniosek jest w realizacji"
      redirect_to order
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_item
      @order_item = OrderItem.find(params[:id])
      @owner_check_object = @order_item
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_item_params
      params.require(:order_item).permit(:order_id, :product_id, :branch_ids => [])
    end

    def check_dane_osobowe
      if @order.products.each do |x|
          if x.dane_osobowe == true
            @order.dane_osobowe = true
            @order.save
          end
        end
      end
    end

    def check_uprawnienia_lokalne
      ub = @order.users.first.branch
      if @order_item.branches.size < 2 && @order_item.branches.include?(ub) 
        @order.uprlok = true
      else 
        @order.uprlok = false
      end
      @order.save
    end
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/views/order_items/_form.haml
= form_for(@order_item) do |f|
 
  .form-inputs
    = collection_check_boxes :order_item, :branch_ids, Branch.all, :id, :nazwa, :item_wrapper_class => 'inline'

  .form-actions
    = f.submit



app/views/order_items/_order_item.haml
.row.order_item
	.span8
		%strong Rola:
		= order_item.product.nr_roli
		= order_item.product.nazwa
		= order_item.product.opis
		%strong DO:
		= order_item.product.dane_osob

		%h5 Obszar widzenia:
		- unless order_item.branches.blank?
			= render order_item.branches
		
		- if order_item.order.niezatwierdzony?
			%p
				= link_to "Dodaj obszar widzenia", edit_order_item_path(order_item)


app/views/order_items/edit.haml
%h1 Editing order_item

= render 'form'

= link_to 'Show', @order_item.order |
= link_to 'Back', @order_item.order


app/views/order_items/index.html.erb
<h1>Listing order_items</h1>

<table>
  <thead>
    <tr>
      <th>Role</th>
      <th>Order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @order_items.each do |order_item| %>
      <tr>
        <td><%= order_item.product_id %></td>
        <td><%= order_item.order_id %></td>
        <td><%= link_to 'Show', order_item %></td>
        <td><%= link_to 'Edit', edit_order_item_path(order_item) %></td>
        <td><%= link_to 'Destroy', order_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order item', new_order_item_path %>

app/views/order_items/new.html.erb
<h1>New order_item</h1>

<%= render 'form' %>

<%= link_to 'Back', order_items_path %>

app/views/order_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Role:</strong>
  <%= @order_item.product_id %>
</p>

<p>
  <strong>Order:</strong>
  <%= @order_item.order_id %>
</p>

<h2>Obszar widzenia:</h2>



<%#= render "areas/form" %>

<!-- <h2>Dodaj obszar widzenia:</h2> -->
	
 -->

<%= link_to 'Edit', edit_order_item_path(@order_item) %> |
<%= link_to 'Back', order_path(@order_item.order) %>