config/routes.rb
Rails.application.routes.draw do
    
  devise_for :users, controllers: {sessions: "sessions", users: "users"}

  concern :the_role, TheRole::AdminRoutes.new

  namespace :admin do
    concerns :the_role
  end

# :controllers => { :sessions => 'users/sessions' }
  
  resources :orders do
    collection do
      get 'wnioski'
    end
    member do
      patch 'zatwierdz'
      patch 'potwierdz'
    end
  resource :decisions
  end

  resources :order_items, only: [:show, :create, :edit, :update, :destroy] do
    resources :areas
  end

  resources :products
  resources :workers
  resources :branches


  get '/pomoc', to: 'static_pages#pomoc'
  get 'static_pages/pomoc'

  root 'products#index'
end

app/models/area.rb
class Area < ActiveRecord::Base
  has_and_belongs_to_many :order_items
end

app/models/branch.rb
class Branch < ActiveRecord::Base
  has_many :users
  has_many :orders, :through => :users
  has_and_belongs_to_many :order_items
	
  validate :nazwa, presence: true

	def to_s
		nazwa
	end
end

app/models/decision.rb
class Decision < ActiveRecord::Base
	belongs_to :order
	
end

app/models/order.rb
class Order < ActiveRecord::Base
	default_scope { order('created_at DESC') }
	scope :nowe, -> { where(status: 1)} #Zaakceptepowane przez wnioskującego
	scope :potw, -> { where(status: 2)} #Zaakceptowane przez Koordynator
	scope :abii, -> { where(status: 4)} #Zaakceptowane przez ABI
	scope :gou, -> { where(status: 8)}	#Zaakceptowane przez GOU
	scope :dane_osob, -> { where(status: 2, dane_osobowe: true)}
	scope :upr_lok, -> { where(uprlok: true) }
	scope :upr_glowne, -> { where(uprlok: false) }

	has_one :decision
	
	has_many :order_items, dependent: :destroy
	has_many :products, through: :order_items
	has_many :branches, through: :users

	has_and_belongs_to_many :users
	has_and_belongs_to_many :contributors, class_name: 'User'


	enum status: [
								:niezatwierdzony, #Status wniosku zainicjowanego
					 			:wobiegu, 				#Status wniosku wysłanego do akceptacji
					 			:potwierdzony, 		#Status wniosku potwierdzonego przez Koordynatora
					 			:kordpopr, 				#Status wniosku wystawionego do poprawy przez Koordynatora
					 			:abipotwierdzam,	#Status wniosku potwierdzonego przez ABI
					 			:odrzucony,				#Status wniosku odrzuconego
					 			:lokpotwierdzam,	#Status wniosku potwierdzonego przez Lokalnego Właściciela Danych
					 			:dyrpotwierdzam,		#Status wniosku potwierdzonego przez Dyrektora
					 			:goupotwierdzam,		#Status wniosku potwierdzonego przez GOU
					 			:gaupotwierdzam
					 											]


	def akcept
		self.wobiegu! if status == "niezatwierdzony" 
	end

	def potwierdzam
		self.potwierdzony! if status == "wobiegu"
	end

	def abi_potwierdzam
		self.abipotwierdzam! if status == "potwierdzony"
	end

	def lok_potwierdzam
		self.lokpotwierdzam! if status == "abipotwierdzam" || status == "potwierdzony"
	end

	def self.lokpotwierdzam?
		status == "lokpotwierdzam"
	end

	def dyr_potwierdzam
		self.dyrpotwierdzam! if status == "abipotwierdzam" || status == "potwierdzony"
	end

	def gou_potwierdzam
		self.goupotwierdzam! if status == "dyrpotwierdzam"
	end

	def gau_potwierdzam
		self.gaupotwierdzam! if status == "goupotwierdzam"
	end

	def brak_zgody
		self.odrzucony!
	end

	def sprawdz_status
		if status == "niezatwierdzony"
			return "Niezatwierdzony"
		elsif status == "wobiegu"
			return "W obiegu"
		elsif status == "potwierdzony"
			return "Potwierdzony przez Koordynatora"
		elsif status == "kordpopr"
			return "Do poprawy"
		elsif status == "abipotwierdzam"
			return "Potwierdzony przez ABI"
		elsif status == "odrzucony"
			return "Wniosek odrzucony"
		elsif status == "lokpotwierdzam"
			return "Potwierdzony przez LOK ADM"
		elsif status == "dyrpotwierdzam"
			return "Potwierdzony przez Dyrektora"
		elsif status == "goupotwierdzam"
			return "Potwierdzony przez GOU"
		elsif status == "gaupotwierdzam"
			return "Wniosek zrealizowany"
		end
	end

	def oddzial_wnioskujacego
		unless users.blank?
			users.first.branch.nazwa
		end
	end

	def upr_lok?
		self.uprlok == true
	end

	def dane_osobowe?
		self.dane_osobowe == true
	end

end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
	belongs_to :order
	belongs_to :product
  has_and_belongs_to_many :branches
  
	validates :product_id, :uniqueness => { :scope => :order_id, :message => "Wnioskujesz już o tą role" }
end

app/models/product.rb
class Product < ActiveRecord::Base

	has_many :order_items
	has_and_belongs_to_many :users
	has_and_belongs_to_many :assistants, 
		class_name: 'User', 
		join_table: 'assistants_products'

	validates :nr_roli, numericality: { only_integer: true, 
		message: "Proszę podać numer" }
	validates :nr_roli, numericality: { greater_than: 0, 
		message: "Numer roli musi być większy od 0" }
			
	validates :nazwa, :opis, presence: true


	def do
		"Przetwarza dane osobowe" if self.dane_osobowe == true
	end

	def dane_osob
		dane_os? ? "TAK" : "NIE"
	end

	def dane_os?
		self.dane_osobowe == true
	end

end

app/models/role.rb
class Role < ActiveRecord::Base
  acts_as_role
end

app/models/user.rb
class User < ActiveRecord::Base
  include TheRole::User
  before_create :set_default_role
  scope :gou, -> { where(role: 8)}

  acts_as_tree order: "email"
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 
  has_and_belongs_to_many :orders
  has_and_belongs_to_many :products

  has_and_belongs_to_many :owned_products, 
    :class_name => "Product", 
    :join_table => "assistants_products"

  has_many :subordinates, class_name: "User",
       foreign_key: "manager_id"
  
  belongs_to :manager, class_name: "User"
  belongs_to :branch


  def kord?
    role == Role.with_name(:kord)
  end

  def kier?
    role == Role.with_name(:kier)
  end

  def abi?
    role == Role.with_name(:abi)
  end

  def lokwl?
    role == Role.with_name(:lokalny_wlasciciel_danych)
  end

  def dyrektor?
    role == Role.with_name(:dyrektor)
  end

  def gou?
    role == Role.with_name(:gou)
  end

  def gau?
    role == Role.with_name(:gau)
  end

  def to_s
  	if imie.blank? || nazwisko.blank?
      email
    else
      imie + ' ' + nazwisko
    end
  end

  def nazwa
    imie + ' ' + nazwisko
  end



  private

  def set_default_role
    self.role ||= Role.with_name(:uzyt)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/helpers/decisions_helper.rb
module DecisionsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sesions_helper.rb
module SesionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/subordinates_helper.rb
module SubordinatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_nav.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="<%= root_url %>">Uprawnienia</a>
      <div class="container nav-collapse">
        <ul class="nav pull-right">
          <li><%= link_to "Pomoc", pomoc_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <% if user_signed_in? %>
                <%= current_user %>
              <% else %>
                Dostęp do portalu
              <% end %>
            <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <% if user_signed_in? %>
                <li>
                  <%= link_to "Twoje wnioski", orders_path %>
                </li>
                <li>
                  <%= link_to "Profil", edit_user_registration_path %>
                </li>
                <% if current_user.admin? %>
                  <li><%= link_to "Uprawnienia", admin_roles_path %></li>
                  <li><%= link_to "Oddziały", branches_path %></li>
                  <li class="divider"></li>
                <% end %>
                <li>
                  <%= link_to "Wyloguj", destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure?' } %>  
                </li>
              <% else %>  
                <li>
                  <%= link_to "Zaloguj", user_session_path %>
                </li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Zarejestruj", new_user_registration_path %>
                </li>
              <% end %>                                                            
            </ul>  
          </li>    
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Uprawnienia" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    
    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <%= render 'layouts/nav' %>

    <div class="container">
      <div class="row">
          <div class="span3">
            <%= yield :role_sidebar %>
          </div>
          <div class="span9">
            <%= yield :role_main %>
          </div>     
      </div>
    </div>
      <div class="container">
        <div class="row">
          <div class="span8">
            <% flash.each do |key, value| %>
            <%= content_tag(:div, value, class: "alert alert-#{key}") %>
            <% end %>
            <%= yield %>
          </div>
            
            <div class="span4">
              <div class="well sidebar-nav">
              <% if user_signed_in? && @order && @order.order_items.present? %>
                <h3>Wniosek</h3>
                <ul class="nav nav-list wniosek">
                  Wnioskujesz o role

                    <% @order.order_items.each do |i| %>
                      <li>
                        <%= i.product.nr_roli %>
                      </li>           
                    <% end %>

                  <h4><%= link_to "Szczegóły wniosku", @order, class: 'btn btn-success btn-block' %></h4>
                </ul>
              <% elsif  user_signed_in? %>
                <h3>Dodaj rolę do wniosku</h3>
                <p><%= link_to "Katalog", products_path, class: 'btn btn-success btn-block' %></p>
              <% else %>
                Aby zawnioskować o uprawnienia musisz być zalogowany.
              <% end %>
              </div><!--/.well -->
            </div><!-- /span3 -->
        </div><!-- /row -->



      <%= debug(params) if Rails.env.development? %>

        <footer>
          <p>&copy; GBS Uprawnienia 2014</p>
        </footer>
      </div> <!-- /container -->
  </body>
</html>

app/views/layouts/strona_domowa.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Uprawnienia" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    
    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <%= render 'layouts/nav' %>
    <div class="container">
      
      <%= yield %>
      

    <%= debug(params) if Rails.env.development? %>

    <footer>
      <p>&copy; GBS Uprawnienia 2014</p>
    </footer>

    </div>
 
  </body>
</html>

app/views/shared/_sub_form.html.erb
<%= form_for(@sub) do |f| %>

<%= f.error_notification %>
	  <div class="form-inputs">
		  <%= f.input :email, required: true, autofocus: true %>
			<%= f.input :password, required: true %>
			<%= f.input :password_confirmation, required: true %>
	  </div>
	  <div class="form-actions">
  		<%= f.submit "Post", class: "btn btn-large btn-primary" %>
		</div>
<% end %>

  